# Generated by Django 3.0 on 2020-04-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, upload_to='news'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='photo',
            field=models.ImageField(blank=True, upload_to='notices'),
        ),
    ]
