# Generated by Django 3.0 on 2020-04-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_slideshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshow',
            name='photo',
            field=models.ImageField(blank=True, upload_to='slideshow'),
        ),
    ]
