# Generated by Django 3.0 on 2020-04-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0008_auto_20200426_1219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
