# Generated by Django 3.0 on 2020-04-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0011_image_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='image_main'),
        ),
    ]
