# Generated by Django 3.0 on 2020-04-29 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0013_auto_20200429_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='slug',
        ),
    ]
