# Generated by Django 3.0 on 2020-05-02 05:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0015_form_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_share_capital', models.IntegerField()),
                ('total_institutional_capital', models.IntegerField()),
                ('total_saving', models.IntegerField()),
                ('total_assets', models.IntegerField()),
                ('total_members', models.IntegerField()),
                ('total_employees', models.IntegerField()),
                ('data_updated_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
