# Generated by Django 3.0.3 on 2020-11-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0018_loans'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loans',
            new_name='Loan',
        ),
    ]
