# Generated by Django 3.0.3 on 2020-11-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0020_auto_20201119_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='traimasik_interest_rate',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
