# Generated by Django 3.0.3 on 2020-11-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0021_auto_20201119_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='loan',
            name='monthly_interest_rate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='loan',
            name='time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='loan',
            name='traimasik_interest_rate',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
