# Generated by Django 3.0.3 on 2020-11-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0022_auto_20201119_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('interest_rate', models.CharField(max_length=100)),
            ],
        ),
    ]
