# Generated by Django 3.0.3 on 2020-11-19 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0023_deposit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deposit',
            new_name='Saving',
        ),
    ]
