# Generated by Django 3.0.3 on 2020-11-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0024_auto_20201119_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='image',
            field=models.FileField(null=True, upload_to='loans_images'),
        ),
        migrations.AddField(
            model_name='loan',
            name='main_text',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
