# Generated by Django 3.0.3 on 2020-11-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0025_auto_20201119_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving',
            name='image',
            field=models.FileField(null=True, upload_to='savings_images'),
        ),
    ]
