# Generated by Django 3.0.3 on 2020-11-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0026_saving_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='code',
            field=models.CharField(blank=True, default='', max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='saving',
            name='code',
            field=models.CharField(blank=True, default='', max_length=8, null=True, unique=True),
        ),
    ]
