# Generated by Django 3.0.3 on 2020-11-19 13:21

from django.db import migrations, models
import first.models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0027_auto_20201119_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='code',
            field=models.CharField(blank=True, default=first.models.generate_unique_code_loan, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='saving',
            name='code',
            field=models.CharField(blank=True, default=first.models.generate_unique_code_saving, max_length=8, null=True, unique=True),
        ),
    ]
