# Generated by Django 3.0.3 on 2020-11-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0029_auto_20201120_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
