# Generated by Django 3.0.3 on 2020-11-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0030_auto_20201120_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='total_share_capital',
            field=models.DecimalField(decimal_places=5, max_digits=100),
        ),
    ]
