# Generated by Django 3.0.3 on 2020-11-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0032_auto_20201120_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='total_assets',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='total_employees',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='total_institutional_capital',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='total_members',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='total_saving',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='total_share_capital',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
