# Generated by Django 3.0.3 on 2020-11-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0033_auto_20201120_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='total_loan',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=100),
            preserve_default=False,
        ),
    ]
