# Generated by Django 3.0.3 on 2020-11-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0034_statistic_total_loan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='data_updated_on',
        ),
        migrations.AlterField(
            model_name='statistic',
            name='total_employees',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='total_members',
            field=models.IntegerField(),
        ),
    ]
