# Generated by Django 3.0.3 on 2020-11-20 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0035_auto_20201120_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='data_updated_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
