# Generated by Django 3.0.3 on 2020-11-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0036_statistic_data_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='total_assets',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='total_employees',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='total_institutional_capital',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='total_loan',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='total_members',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='total_saving',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='total_share_capital',
            field=models.CharField(max_length=500),
        ),
    ]
