# Generated by Django 3.0.3 on 2020-11-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0037_auto_20201120_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other_program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('code', models.CharField(blank=True, default='', max_length=8, null=True, unique=True)),
                ('main_text', models.CharField(max_length=1000)),
                ('image', models.FileField(null=True, upload_to='otherprograms_images')),
            ],
        ),
    ]
