# Generated by Django 3.0.3 on 2020-11-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0038_other_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other_program',
            name='code',
            field=models.CharField(blank=True, default='generate_unique_code_other', max_length=8, null=True, unique=True),
        ),
    ]
