# Generated by Django 3.0.3 on 2020-11-21 15:38

from django.db import migrations, models
import first.models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0039_auto_20201121_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other_program',
            name='code',
            field=models.CharField(blank=True, default=first.models.generate_unique_code_other, max_length=8, null=True, unique=True),
        ),
    ]
