# Generated by Django 3.0.3 on 2020-11-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0040_auto_20201121_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshow',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
