from . import views
from django.urls import path
from .views import NoticeDetailView, VideoDetailView

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('aboutus.html', views.aboutus, name='aboutus'),
    path('org_profile.html', views.org_profile, name='org_profile'),
    path('vision.html', views.vision, name='vision'),
    path('management_team.html', views.management_team, name='management_team'),
    path('communication_team.html', views.communication_team,
         name='communication_team'),
    path('probesan_team.html', views.probesan_team, name='probesan_team'),
    path('other_teams.html', views.other_teams, name='other_teams'),
    path('account.html', views.account, name='account'),
    path('loan.html', views.loan, name='loan'),
    path('employees.html', views.employees, name='employees'),
    path('branch_office.html', views.branch_office, name='branch_office'),
    path('savings.html', views.savings, name='savings'),
    path('term_deposits.html', views.term, name='term'),
    path('insurance.html', views.insurance, name='insurance'),
    path('remittance.html', views.remittance, name='remittance'),
    path('loans.html', views.loans, name='loans'),
    path('other_programs.html', views.other_programs, name='other_programs'),
    path('msg_chairperson.html', views.msg_chairperson, name='msg_chairperson'),
    path('msg_manager.html', views.msg_manager, name='msg_manager'),
    path('policies.html', views.policies, name='policies'),
    path('forms.html', views.forms, name='forms'),
    path('reports.html', views.reports, name='reports'),
    path('notice.html', views.notice, name='notice'),
    path('photo.html', views.photo, name='photo'),
    path('photo/<int:id>/', views.photo_detail, name='photo-detail'),
    path('video.html', views.video, name='video'),
    path('video/<int:pk>/', VideoDetailView.as_view(), name='video-detail'),
    path('calender.html', views.calender, name='calender'),
    path('affiliations.html', views.affiliations, name='affiliations'),
    path('contact.html', views.contact, name='contact'),
    path('notice/<int:pk>/', NoticeDetailView.as_view(), name='notice-detail'),
]
